# Generated by Django 4.1.7 on 2023-02-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('renewal_date', models.DateTimeField(max_length=50)),
                ('start_date', models.DateTimeField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('membership', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
