# Generated by Django 4.2.5 on 2023-09-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_record_phone_remove_record_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='monthly_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
