# Generated by Django 4.2.5 on 2023-09-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_monthly_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
    ]
