# Generated by Django 4.2.5 on 2023-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_record_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
