# Generated by Django 4.2.5 on 2023-09-23 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_record_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='renewal',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
