# Generated by Django 4.2.5 on 2023-09-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_record_renewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='renewal',
        ),
    ]
