# Generated by Django 4.2.5 on 2023-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_record_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
